cc_test(
    name = "priorityq",
    srcs = ["priorityq_test.cc"],
    deps = [
        "//src:common",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "lines",
    srcs = ["lines_test.cc"],
    deps = [
        "//src:common",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
