package(default_visibility = ["//visibility:public"])

cc_library(
    name = "common",
    srcs = [
        "apib_lines.c",
        "apib_priorityq.c",
    ],
    hdrs = [
        "apib_lines.h",
        "apib_priorityq.h",
    ],
)
